# Generated by Django 4.1.7 on 2024-01-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txtAct', models.CharField(max_length=6)),
                ('fecha', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=1)),
            ],
        ),
    ]
